### ISSUE TITLE
Unable to send metrics to Grafana Cloud

### ISSUE THREAD

**Issue by dalareo** [Pierre-Lannoy/wp-decalog#50]
**Describe the bug**
Hi, we are trying to set up Prometheus metrics as explained in https://perfops.one/a-almost-free-observability-platform-part-2/ but we are not able to get metrics in Grafana Cloud.

**To Reproduce**
1. Set Prometheus endpoint in Decalog Plugin. Wordpress is deployed inside Kubernetes cluster exposed by a service
2. Set Grafana Agent inside the cluster with the following config:

````
    metrics:
      wal_directory: /var/lib/agent/wal
      global:
        scrape_interval: 60s
        external_labels:
          cluster: 'clustername'
      configs:
      - name: integrations
        remote_write:
        - url: https://prometheus-prod-05-gb-south-0.grafana.net/api/prom/push
          basic_auth:
            username: 'username'
            password: 'password'
        scrape_configs:
        - job_name: decalog/scrapping
          static_configs:
            - targets: ['service-name']
              labels:
                process: 'agent'
          metrics_path: "/wp-json/decalog/v3/metrics?uuid=XXXXXX"
````

3. Go to grafana.com
4. Only scrape_duration_seconds metrics are shown with the selected labels

**Expected behavior**
All metrics send by Decalog (those with wordpress_ prefix) are expected to be present. We are able to get Prometheus metrics in local Grafana using Push Gateway, but with Grafana Cloud we cannot use it.

**Environment (please complete the following information):**
 - PHP version:PHP 7.4
 - WordPress 6.1

**Additional context**
